FROM selenium/standalone-chrome:latest

USER root
RUN mkdir -p /var/lib/apt/lists/partial && \
    chmod -R 755 /var/lib/apt/lists && \
    apt-get update && \
    apt-get install -y python3 python3-pip git

COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt

COPY . /app
COPY geodnet_scraper_updated.py /app/geodnet_scraper.py

WORKDIR /app

CMD ["python3", "geodnet_scraper.py"]